### PR TITLE
Asciidoctorjs 3

### PR DESCRIPTION
**Pull request by xavier-calland**
Issue #89

### CODE REVIEW

**Comment by ggrossetie** [comment]
Thanks!
Could you please extract the CDN update (from `https://twemoji.maxcdn.com` to `https://cdn.jsdelivr.net/npm/twemoji@latest`) into a dedicated pull request?

Also, we need to say on `"libnpmpublish": "~6.0"`. They frequently introduce breaking changes and as a result our `publish` task is probably not working with anything > 6.x.

Any reason to use `^` instead of `~` ? I would prefer to keep using `~x.y` (unless you have a strong case for `^`).

**Comment by xavier-calland** [comment]
If the lib uses and respects SemVer(it may be a too big assomption), we can use `^x.y` without risk. It will only use version `x.z` (with `z` >= `y`), so no breaking changes will be introduced.
This allows automatic updates with `npm update`.

If you prefer using `~`, no problem :)

I prepare a PR for the CDN update.

**Comment by ggrossetie** [comment]
I've updated dependencies in https://github.com/ggrossetie/asciidoctor-emoji/commit/85959ac9081bc1bd150e17cc78bbf42a27213b48.
I just released version 0.5.0. Could you please give it a try?

**Comment by xavier-calland** [comment]
Version 0.5.0 work fine for me.
Thanks !

**Pull request closed without merging**
